### ISSUE TITLE
FeatureBee with (micro) services

### ISSUE THREAD

**Issue by smalldave** [AutoScout24/FeatureBee#69]
A quick question.
I've read one of the AutoScout24 blog posts that mentioned you were moving to microservices.
Does FeatureBee play nicely in this environment? 
For instance say I want to turn a feature on for a given user in service A
The initial request from the user hits service B. Service B calls service A for some information and it's here we want the new feature to kick in. How does Service B get the context it needs to evaluate the state of the feature?
Hope I've described that in a way that makes sense.

**Comment by pgarbe** [comment]
The quick answer is no. FeatureBee plays best when you have a single (monolithic) web application. 

Right now we are at the beginning on our journey to microservices. Have a look on our new [Tech-Blog](http://inside.autoscout24.com) for more information. As we are already addicted to release features fast and easy I guess we'll come up with a solution when we need it. Unfortunately at the moment I can't say when and how it would look like.

**Comment by smalldave** [comment]
Thanks. Had a quick look at your blog and it sounds like it will look like something based on the JVM!
A bold decision (and I think the right one). Good luck.
